import { useState } from "react";
import { Link } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Wordmark } from "@/components/Wordmark";
import { Button } from "@/components/ui/button";
import { GoldRule } from "@/components/Ornaments";
import { toast } from "sonner";

const DEMO_USERS = [
  {
    id: "11111111-1111-1111-1111-111111111111",
    name: "Mara, 44",
    blurb: "Perimenopausal transition. FSH 38, E2 94, ferritin 28, vitamin D 42. Severe night sweats, early waking, rage, low libido.",
    mode: "transition",
  },
  {
    id: "22222222-2222-2222-2222-222222222222",
    name: "Eve, 28",
    blurb: "Regular 28-day cycles. Bloods all within range. Moderate luteal-phase PMS for 7 days each month. No major flags.",
    mode: "cycle",
  },
  {
    id: "33333333-3333-3333-3333-333333333333",
    name: "Helen, 56",
    blurb: "Three years post-menopause, on transdermal HRT for two. Vitamin D 38 (low). Joint pain, dry skin, mild brain fog. Healthspan focus.",
    mode: "post_meno",
  },
];

type ProtocolResult = {
  cached: boolean;
  protocol: any;
};

export default function ProtocolDemo() {
  const [loadingId, setLoadingId] = useState<string | null>(null);
  const [result, setResult] = useState<ProtocolResult | null>(null);
  const [activeUser, setActiveUser] = useState<string | null>(null);

  async function generate(userId: string, force: boolean) {
    setLoadingId(userId);
    setActiveUser(userId);
    setResult(null);
    try {
      const { data, error } = await supabase.functions.invoke("generate-protocol", {
        body: { user_id: userId, force_regenerate: force },
      });
      if (error) throw error;
      if ((data as any)?.error) throw new Error((data as any).error);
      setResult(data as ProtocolResult);
      toast.success(
        (data as any).cached
          ? "Loaded cached protocol"
          : "Protocol generated by Claude",
      );
    } catch (e) {
      console.error(e);
      toast.error(e instanceof Error ? e.message : "Failed to generate protocol");
    } finally {
      setLoadingId(null);
    }
  }

  const protocol = result?.protocol;

  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="flex items-center justify-between px-6 md:px-12 py-6 border-b border-border-soft">
        <Wordmark size="sm" variant="text-only" />
        <Link to="/" className="text-sm text-muted-foreground hover:text-foreground">
          Back to home
        </Link>
      </header>

      <main className="max-w-5xl mx-auto px-6 md:px-12 py-12 md:py-16">
        <div className="mb-10">
          <p className="text-xs uppercase tracking-[0.36em] text-gold-deep mb-4">
            Protocol engine, demo mode
          </p>
          <h1 className="font-display text-4xl md:text-6xl text-foreground mb-4">
            Synthetic profiles only.
          </h1>
          <p className="text-muted-foreground max-w-2xl leading-relaxed">
            This is the v1 Anadya protocol engine. It reads each user's bloods, cycle data,
            symptom log and goals, then generates a supplement stack, lifestyle plan and GP
            escalation flags in Marc's voice. Real users are gated behind the legal review.
          </p>
          <GoldRule className="text-gold mt-8 max-w-xs" />
        </div>

        <section className="grid md:grid-cols-3 gap-5 mb-12">
          {DEMO_USERS.map((u) => (
            <div
              key={u.id}
              className={`card-elevated p-6 flex flex-col ${
                activeUser === u.id ? "ring-1 ring-gold" : ""
              }`}
            >
              <p className="text-xs uppercase tracking-[0.3em] text-gold-deep mb-2">
                {u.mode.replace("_", " ")}
              </p>
              <h2 className="font-display text-2xl mb-3">{u.name}</h2>
              <p className="text-sm text-muted-foreground leading-relaxed flex-1">
                {u.blurb}
              </p>
              <div className="mt-5 flex gap-2">
                <Button
                  className="btn-primary flex-1"
                  disabled={loadingId !== null}
                  onClick={() => generate(u.id, false)}
                >
                  {loadingId === u.id ? "Generating..." : "Generate"}
                </Button>
                <Button
                  variant="outline"
                  className="border-gold text-gold-deep hover:bg-gold-soft"
                  disabled={loadingId !== null}
                  onClick={() => generate(u.id, true)}
                  title="Force regenerate, bypass 14-day cache"
                >
                  Re-run
                </Button>
              </div>
            </div>
          ))}
        </section>

        {protocol && (
          <article className="card-elevated p-8 md:p-12">
            <p className="text-xs uppercase tracking-[0.3em] text-gold-deep mb-2">
              {result?.cached ? "Cached protocol" : "Fresh protocol"} ·{" "}
              {protocol.mode}
            </p>
            <h2 className="font-display text-3xl md:text-4xl mb-6">Protocol summary</h2>
            <p className="text-foreground leading-relaxed mb-10 whitespace-pre-line">
              {protocol.summary}
            </p>

            <GoldRule className="text-gold mb-10" />

            <h3 className="font-display text-2xl mb-4">Supplement stack</h3>
            <div className="space-y-4 mb-10">
              {protocol.supplement_stack?.map((s: any) => (
                <div key={s.sku_id} className="border border-border-soft rounded-sm p-5 bg-cream">
                  <div className="flex items-baseline justify-between mb-2 gap-3 flex-wrap">
                    <h4 className="font-display text-xl">{s.name}</h4>
                    <span className="text-xs uppercase tracking-[0.2em] text-gold-deep">
                      {s.priority} priority · {s.duration_weeks} wk
                    </span>
                  </div>
                  <p className="text-sm text-muted-foreground leading-relaxed mb-3">
                    {s.rationale}
                  </p>
                  <p className="text-sm text-foreground">
                    £{(s.price_monthly_pence / 100).toFixed(2)}/mo · £
                    {(s.price_oneoff_pence / 100).toFixed(2)} one-off
                  </p>
                </div>
              ))}
            </div>

            <h3 className="font-display text-2xl mb-4">Lifestyle</h3>
            <div className="space-y-4 mb-10">
              {protocol.lifestyle_recommendations?.map((l: any, i: number) => (
                <div key={i} className="border-l-2 border-gold pl-5">
                  <p className="text-xs uppercase tracking-[0.2em] text-gold-deep mb-1">
                    {l.category.replace("_", " ")}
                  </p>
                  <h4 className="font-display text-xl mb-2">{l.headline}</h4>
                  <p className="text-sm text-muted-foreground leading-relaxed">{l.detail}</p>
                  {l.evidence_ref && (
                    <p className="text-xs text-text-dim mt-2 italic">{l.evidence_ref}</p>
                  )}
                </div>
              ))}
            </div>

            {protocol.escalation_flags?.length > 0 && (
              <>
                <h3 className="font-display text-2xl mb-4">GP escalation</h3>
                <div className="space-y-4 mb-10">
                  {protocol.escalation_flags.map((f: any, i: number) => (
                    <div
                      key={i}
                      className={`border rounded-sm p-5 ${
                        f.urgency === "urgent"
                          ? "border-rose-deep bg-rose-soft"
                          : "border-gold bg-gold-soft"
                      }`}
                    >
                      <div className="flex items-baseline justify-between mb-2 gap-3 flex-wrap">
                        <h4 className="font-display text-lg">
                          {f.marker_or_symptom}: {f.value}
                        </h4>
                        <span className="text-xs uppercase tracking-[0.2em] text-gold-deep">
                          {f.urgency} · {f.type}
                        </span>
                      </div>
                      <p className="text-sm text-foreground leading-relaxed mb-3">{f.reason}</p>
                      <p className="text-xs text-muted-foreground italic leading-relaxed">
                        Ask your GP: {f.draft_gp_question}
                      </p>
                    </div>
                  ))}
                </div>
              </>
            )}

            <h3 className="font-display text-2xl mb-4">Read next</h3>
            <ul className="space-y-2">
              {protocol.content_feed?.map((c: any) => (
                <li key={c.slug} className="text-sm">
                  <span className="text-gold-deep">→</span>{" "}
                  <span className="text-foreground">{c.slug}</span>
                  <span className="text-muted-foreground"> · {c.reason}</span>
                </li>
              ))}
            </ul>
          </article>
        )}
      </main>
    </div>
  );
}
